"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/index.jsx";
import { createContext, useReducer, useState } from "react";
import Cart from "@/components/Cart/index.jsx";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const CartContext = createContext();

export default function RootLayout({ children }) {
  const [state, dispatch] = useReducer(
    (state, action) => {
      switch (action) {
        case "TOGGLE_CART":
          return { ...state, isCartOpen: !state.isCartOpen };
        default:
          return state;
      }
    },
    {
      isCartOpen: false,
    }
  );

  const handleToggleCart = (bool) => {
    dispatch("TOGGLE_CART", { isCartOpen: bool });
  };

  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <CartContext.Provider value={{ state, dispatch }}>
          <div className="bg-white">
            <button onClick={() => dispatch()} />
            <Header isCartOpen={state?.isCartOpen} />
            {children}
            <Cart open={state?.isCartOpen} setOpen={handleToggleCart} />
          </div>
        </CartContext.Provider>
      </body>
    </html>
  );
}
